name: ROS 2 CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    name: ROS 2 ${{ matrix.ros_distribution }} on Ubuntu ${{ matrix.ubuntu_codename }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.ubuntu_codename }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: jazzy
            ubuntu_codename: noble
            use_ros2_testing: false
          - ros_distribution: lyrical
            ubuntu_codename: resolute
            use_ros2_testing: false
          - ros_distribution: rolling
            ubuntu_codename: resolute
            use_ros2_testing: true
    steps:
      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          use-ros2-testing: ${{ matrix.use_ros2_testing }}

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          coverage-result: false
