on:
  pull_request:
  push:
      
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
        ros_distribution: [foxy, galactic, humble, rolling]
      fail-fast: false
    steps:
      - name: add more dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-coveragepy-result \
            ros-${{ matrix.ros_distribution }}-diagnostic-updater
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
