on:
  pull_request:
  push:
      
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ros_distribution: [foxy, galactic]
      fail-fast: false
    steps:
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
